[project]
name = "telegrambot"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "aiogram>=3.19.0",
    "aiohttp>=3.11.14",
    "pydantic>=2.10.6",
    "ruff>=0.11.2",
]
